name: cppcheck-action-test
on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build:
    name: cppcheck-test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: cppcheck
      uses: deep5050/cppcheck-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN}}
        other_options: --language=c++ --std=c++17 --enable=all --addon=cert.py
        output_file: .github/cppcheck_report.txt
